namespace EImza.BlazorServer.Models;

public enum DocumentType
{
    Unknown,
    RawText,
    Xml,
    Pdf
}

public enum ContentType
{
    RawText,
    Xml,
    Pdf
}

public class CertificateInfo
{
    public Guid Id { get; set; }
    public string Subject { get; set; } = string.Empty;
    public string Issuer { get; set; } = string.Empty;
    public DateTime ValidFrom { get; set; }
    public DateTime ValidTo { get; set; }
    public bool IsAutoGenerated { get; set; }
    public byte[]? CertificateData { get; set; }
    public string? Password { get; set; }
    public int KeySizeBits { get; set; } = 2048;
}

public class SigningRequest
{
    public ContentType ContentType { get; set; }
    public byte[] Content { get; set; } = Array.Empty<byte>();
    public string FileName { get; set; } = string.Empty;
    public CertificateInfo? Certificate { get; set; }

    public string ContentAsString =>
        ContentType == ContentType.RawText || ContentType == ContentType.Xml
            ? System.Text.Encoding.UTF8.GetString(Content)
            : throw new InvalidOperationException("Not a text-based content type");

    public string FileNameWithSuffix
    {
        get
        {
            var nameWithoutExt = Path.GetFileNameWithoutExtension(FileName);
            var ext = Path.GetExtension(FileName);
            return $"{nameWithoutExt}_signed{ext}";
        }
    }
}

public class SigningResult
{
    public byte[] SignedContent { get; set; } = Array.Empty<byte>();
    public string FileId { get; set; } = string.Empty;
    public string OriginalFileName { get; set; } = string.Empty;
    public string SignedFileName { get; set; } = string.Empty;
    public ContentType ContentType { get; set; }
    public DateTimeOffset Timestamp { get; set; } = DateTimeOffset.UtcNow;
    public byte[]? Signature { get; set; }
    public byte[]? Hash { get; set; }
    public string HashAlgorithm { get; set; } = "SHA256";
    public string? ErrorMessage { get; set; }
}

public class VerificationRequest
{
    public byte[] Content { get; set; } = Array.Empty<byte>();
    public string FileName { get; set; } = string.Empty;
}

public class VerificationResult
{
    public bool IsValid { get; set; }
    public DocumentType DocumentType { get; set; }
    public List<SignatureInfo> Signatures { get; set; } = new();
    public string ErrorMessage { get; set; } = string.Empty;
    public CertificateInfo? Certificate { get; set; }
}

public class SignatureInfo
{
    public string Signer { get; set; } = string.Empty;
    public DateTime SigningTime { get; set; }
    public string HashAlgorithm { get; set; } = string.Empty;
    public bool IsSignatureValid { get; set; }
    public bool IsDocumentModified { get; set; }
}
