<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\SigningService\SigningService.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazored.SessionStorage" Version="2.4.0" />
    <PackageReference Include="MudBlazor" Version="7.15.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
