using EImza.BlazorServer.Components;
using EImza.BlazorServer.Services;
using Microsoft.AspNetCore.Http.Features;
using SigningService.Crypto;
using SigningService.Raw;
using SigningService.Xml;
using SigningService.Pdf;
using MudBlazor.Services;
using Blazored.SessionStorage;

var builder = WebApplication.CreateBuilder(args);

// Add MudBlazor services
builder.Services.AddMudServices();

// Add session storage
builder.Services.AddBlazoredSessionStorage();

// Configure file upload limits
builder.Services.Configure<FormOptions>(options =>
{
    options.MultipartBodyLengthLimit = 104857600; // 100MB
});

// Add services to the container.
builder.Services.AddRazorComponents()
    .AddInteractiveServerComponents();

// Register SigningService dependencies
builder.Services.AddTransient<ISigner, SoftwareSigner>();
builder.Services.AddTransient<RawSigningService>();
builder.Services.AddTransient<XmlSigningService>();
builder.Services.AddTransient<PdfSigningService>(sp =>
{
    var signer = sp.GetRequiredService<ISigner>();
    var cert = signer is SoftwareSigner ss
        ? ss.CreateSelfSignedCertificate("CN=EImzaAutoGenerated")
        : throw new InvalidOperationException("Signer must be SoftwareSigner");
    return new PdfSigningService(signer, cert);
});

// Register application services
builder.Services.Configure<FileStorageOptions>(builder.Configuration.GetSection("FileStorage"));
builder.Services.AddScoped<CertificateService>();
builder.Services.AddScoped<FileStorageService>();
builder.Services.AddScoped<SigningOrchestratorService>();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error", createScopeForErrors: true);
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();


app.UseAntiforgery();

// Download endpoint for signed documents
app.MapGet("/api/download/{fileId:guid}", async (
    Guid fileId,
    FileStorageService storage,
    CancellationToken cancellationToken) =>
{
    var file = await storage.GetFileAsync(fileId.ToString(), cancellationToken);
    if (file == null)
        return Results.NotFound();

    var fileInfo = await storage.GetFileInfoAsync(fileId.ToString(), cancellationToken);
    return Results.File(file, "application/octet-stream", fileInfo?.Name ?? $"signed_document_{fileId}");
});

app.MapStaticAssets();
app.MapRazorComponents<App>()
    .AddInteractiveServerRenderMode();

app.Run();
