using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using EImza.BlazorServer.Models;
using SigningService.Crypto;

namespace EImza.BlazorServer.Services;

public class CertificateService
{
    private readonly ILogger<CertificateService> _logger;

    public CertificateService(ILogger<CertificateService> logger)
    {
        _logger = logger;
    }

    public async Task<CertificateInfo> UploadCertificateAsync(Stream certificateStream, string password)
    {
        using var ms = new MemoryStream();
        await certificateStream.CopyToAsync(ms);
        var certBytes = ms.ToArray();

        X509Certificate2? cert = null;
        try
        {
            cert = new X509Certificate2(certBytes, password,
                X509KeyStorageFlags.Exportable | X509KeyStorageFlags.EphemeralKeySet);
        }
        catch (CryptographicException ex)
        {
            _logger.LogError(ex, "Failed to load certificate with provided password");
            throw new InvalidOperationException("Invalid certificate password or corrupted certificate file.", ex);
        }

        // Validate certificate has private key
        if (!cert.HasPrivateKey)
        {
            throw new InvalidOperationException("Certificate must have a private key for signing.");
        }

        // Validate RSA key
        using var rsa = cert.GetRSAPrivateKey();
        if (rsa == null)
        {
            throw new InvalidOperationException("Certificate must have an RSA private key.");
        }

        var certInfo = new CertificateInfo
        {
            Id = Guid.NewGuid(),
            Subject = cert.Subject,
            Issuer = cert.Issuer,
            ValidFrom = cert.NotBefore,
            ValidTo = cert.NotAfter,
            IsAutoGenerated = false,
            CertificateData = certBytes,
            Password = password,
            KeySizeBits = rsa.KeySize
        };

        _logger.LogInformation("Certificate loaded successfully: {Subject}", cert.Subject);

        return certInfo;
    }

    public CertificateInfo GenerateCertificate(string subjectName = "CN=EImzaAutoGenerated")
    {
        using var signer = new SoftwareSigner();
        var cert = signer.CreateSelfSignedCertificate(subjectName);

        return new CertificateInfo
        {
            Id = Guid.NewGuid(),
            Subject = cert.Subject,
            Issuer = cert.Issuer,
            ValidFrom = cert.NotBefore,
            ValidTo = cert.NotAfter,
            IsAutoGenerated = true,
            CertificateData = cert.Export(X509ContentType.Pfx, ""),
            Password = "",
            KeySizeBits = 2048
        };
    }

    public X509Certificate2 GetCertificateForSigning(CertificateInfo certInfo)
    {
        if (certInfo.CertificateData == null)
            throw new InvalidOperationException("Certificate data not available");

        return new X509Certificate2(certInfo.CertificateData, certInfo.Password ?? "",
            X509KeyStorageFlags.Exportable | X509KeyStorageFlags.EphemeralKeySet);
    }

    public bool ValidatePassword(Stream certificateStream, string password)
    {
        try
        {
            using var ms = new MemoryStream();
            certificateStream.CopyToAsync(ms).Wait();
            var certBytes = ms.ToArray();

            using var cert = new X509Certificate2(certBytes, password,
                X509KeyStorageFlags.Exportable | X509KeyStorageFlags.EphemeralKeySet);

            return cert.HasPrivateKey;
        }
        catch
        {
            return false;
        }
    }

    public void ClearSensitiveData(CertificateInfo certInfo)
    {
        certInfo.Password = null;
        certInfo.CertificateData = null;
    }
}
